name: CI

on: [push]

jobs:
  windows:
    name: windows-${{ matrix.buildtype }}
    runs-on: windows-latest
    strategy:
      matrix:
        buildtype: [Debug, RelWithDebInfo, MinSizeRel]

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Setup MSYS"
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            git
            make
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-gtkmm3

      - name: "Build"
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} ..
          ninja

      - name: "Setup Artifact"
        run: |
          mkdir build/artifactdir
          cd build
          ls -la
          cp *.exe artifactdir
          cd ..
          cat "ci/deps.txt" | sed 's/\r$//' | xargs -I % cp /mingw64% build/artifactdir

      - name: "Upload Build"
        uses: actions/upload-artifact@v2
        with:
          name: build-windows-${{ matrix.buildtype }}
          path: build/artifactdir